name: curving_reality_library
description: "The Curving Reality Flutter Library is designed to accelerate your app development workflow. It provides a rich collection of efficient and visually appealing UI components, ready-to-use screens, and practical services, including powerful tools for forms validation."
version: 1.0.0
homepage: https://www.curvingreality.com/
repository: https://github.com/curvingreality/flutter-library/
issue_tracker: https://github.com/curvingreality/flutter-library/issues

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.3.1
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  #assets:
